site_name: Microsoft 365 Lab
site_url: https://microsoft-365-labs.gtzlabs.com/
site_author: GTZ Labs
nav:
    - Home: index.md
    - AD: \docs\Active-Directory\Active-Directory-Install.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/efrain-gutierrez-4909b51a5/

repo_url: https://github.com/Zephron-gtz/Microsoft-365-Labs
repo_name: Zephron-gtz/Microsoft-365-Labs


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - footnotes
  - def_list
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format