site_name: Microsoft 365 Lab
nav:
    - Home: index.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt 

repo_url: https://github.com/Zephron-gtz/Microsoft-365-Labs
repo_name: Zephron-gtz/Microsoft-365-Labs


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - footnotes
  - def_list
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format